[Server]
# Base url of your linx-server instance
linx_instance_url = "https://greatestlinxserver.com"
# API key you generated and put into your authfile
linx_api_key = "great-password"

[Defaults]
# Default amount of expiry in days
default_expiry_days = 90
